server:
  port: 8081
spring:
  application:
    name: accounts-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: accounts_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts_schema
  security:
    oauth2:
      client:
        registration:
          keycloak-client-credentials:
            provider: keycloak
            client-id: <client-id>            # например, cash-service
            client-secret: <client-secret>
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
