server:
  port: 8081
spring:
  application:
    name: accounts-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: accounts_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts_schema
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
