spring:
  application:
    name: cash-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: cash_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: cash_schema
  security:
    oauth2:
      client:
        registration:
          keycloak-client-credentials:
            provider: keycloak
            client-id: cash-service
            client-secret: u8ANCW8BcqwJvGZMlYTfATVfpF8UZXwI
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8089/realms/bankapp/protocol/openid-connect/token
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

gateway:
  base-url: http://localhost:8088
