spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: exchange_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: exchange_schema
  security:                                               #last changes START
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bankapp    #last changes END

server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: exchange-service       
