spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: front-ui
#          uri: lb://front-ui
#          predicates:
#            - Path=/, /main/**, /signup/**, /css/**, /js/**, /images/**

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**

        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash/**

        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**

        - id: exchange-generator-service
          uri: lb://exchange-generator-service
          predicates:
            - Path=/exchange-generator/**

        - id: blocker-service
          uri: lb://blocker-service
          predicates:
            - Path=/blocker/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/notifications/**
      default-filters:
        - TokenRelay
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080,http://localhost:8088"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true      #last changes END

  security:
    oauth2:
      client:                                                   #last changes START
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway
            client-secret: XAIm6TbEps7OeCmWs4u9GH5GLZC2vL0A
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/bankapp    #last changes END
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bankapp

server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: gateway-service


