spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**

        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash/**

        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**

        - id: exchange-generator-service
          uri: lb://exchange-generator-service
          predicates:
            - Path=/exchange-generator/**

        - id: blocker-service
          uri: lb://blocker-service
          predicates:
            - Path=/blocker/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/bankapp

server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


