spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: transfer_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: transfer_schema
  security:
    oauth2:
      client:
        registration:
          keycloak-client-credentials:
            provider: keycloak
            client-id: transfer-service
            client-secret: PKnPEv23xSGCbl50Z6tXxU6rS4PsBIZG
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8089/realms/bankapp/protocol/openid-connect/token

server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
